version: v1.0
name: "🚀 Deploy to production (Demo Only)"

agent:
  machine:
    type: f1-standard-2
    os_image: ubuntu2404

fail_fast:
  stop:
    when: branch != 'main'

global_job_config:
  prologue:
    commands:
      - |
        run_or_pass() {
          echo "→ $*"
          # simulate success regardless of real outcome
          return 0
        }
      - run_or_pass "checkout"

blocks:
  - name: "🧱 Build & Push"
    task:
      jobs:
        - name: Docker image
          commands:
            - echo "🔨 Building Docker image ${DOCKER_IMAGE}:${SEMAPHORE_GIT_SHA}"
            - echo "📤 Pushing image to registry..."

  - name: "🚢 Deploy"
    task:
      jobs:
        - name: Update deployment
          commands:
            - echo "🚀 Deploying ${DOCKER_IMAGE}:${SEMAPHORE_GIT_SHA} to ${KUBE_NAMESPACE} namespace"
            - echo "⏳ Waiting for rollout to complete..."

  - name: "🩺 Check"
    task:
      jobs:
        - name: Health check
          commands:
            - echo "🔍 Checking health at ${HEALTH_URL}"
            - echo "✅ Deployment successful (simulated)"
